build:
  version: "1.0"

areas:
  message: "Welcome to Pocket-Ticket areas related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
